### ISSUE TITLE
using CardBanner in fragment

### ISSUE THREAD

**Issue by hosseinjafari9574** [fengminchao/CardBanner#4]
Hi again @fengminchao 
I have problem when using CardBanner in fragment.
I have some fragments as a bottom navigation when I navigate between them and come back to the main that contain CardBanner, I can't see banner anymore and sometimes after a while it show up.

it's a bug or I have done something wrong in implementation? what do you think?

Thank you so much 👍

**Comment by fengminchao** [comment]
If you only hide or show fragments when you navigate between them it won't happen. Can you show me the code about using fragment?

**Comment by hosseinjafari9574** [comment]
`    bottomNavigation.setOnTabSelectedListener(new AHBottomNavigation.OnTabSelectedListener() {
            @Override
            public boolean onTabSelected(int position, boolean wasSelected) {
                FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
                switch (position) {
                    case 0:
                        ft.replace(R.id.frmContainer,catFragment );
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;

                    case 1:
                        ft.replace(R.id.frmContainer, searchFragment);
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;

                    case 2:
                        ft.replace(R.id.frmContainer, profileFragment);
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;

                    case 3:
                        ft.replace(R.id.frmContainer, homeFragment);
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;
                }
                return true;
            }
        });`

**Comment by hosseinjafari9574** [comment]
here it is 👍 
```
bottomNavigation.setOnTabSelectedListener(new AHBottomNavigation.OnTabSelectedListener() {
            @Override
            public boolean onTabSelected(int position, boolean wasSelected) {
                FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
                switch (position) {
                    case 0:
                        ft.replace(R.id.frmContainer,catFragment );
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;

                    case 1:
                        ft.replace(R.id.frmContainer, searchFragment);
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;

                    case 2:
                        ft.replace(R.id.frmContainer, profileFragment);
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;

                    case 3:
                        ft.replace(R.id.frmContainer, homeFragment);
                        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                        ft.commit();
                        break;
                }
                return true;
            }
        });

```

**Comment by fengminchao** [comment]
The bug will happen when you use cardbanner in fragment because of fragment lifecycle. I fixed it in version 1.1.2. Thanks for your feedback!👍

**Comment by hosseinjafari9574** [comment]
thank you for your attention :)

**Comment by hosseinjafari9574** [comment]
Hi again ... after update and navigate between fragment I got a force_close. This is my error log :
```
02-23 10:19:00.836 3882-3882/sarinapp.ir.mr_tea E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sarinapp.ir.mr_tea, PID: 3882
    java.lang.RuntimeException: The size of viewHolders and data should be same
        at com.muxistudio.cardbanner.CardPagerAdapter.<init>(CardPagerAdapter.java:43)
        at com.muxistudio.cardbanner.CardBanner.setViewHolders(CardBanner.java:119)
        at sarinapp.ir.mr_tea.package_home.HomeFragment.bannerFunctions(HomeFragment.java:152)
        at sarinapp.ir.mr_tea.package_home.HomeFragment.onCreateView(HomeFragment.java:60)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2530)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1233)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1299)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:688)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2069)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1859)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1814)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by fengminchao** [comment]
`java.lang.RuntimeException: The size of viewHolders and data should be same`

Check the size of viewHolders and data is the same.

**Comment by hosseinjafari9574** [comment]
I add below code before for loop and it works good 👍 


` mViewHolders.clear();
`

THANK YOU SO MUCH  ^___^
